---
title: "Fórmulas"
author: "AS"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Medidas de Regressão

- Variância

$$S^2=\frac{\sum_{n=1}^{N}\left(y_i-\bar{y}\right)^2}{n}$$

- Deviance Métrica

$$DEV^{\mathrm{met\ }}=\sum_{n=1}^{N}\left(y_i-\bar{y}\right)^2$$





- Residual Sum of Squares (RSS) or Sum of Squares error (SSE)

$$\sum\left(y_i-{\hat{y}}_i\right)^2$$

- Mean Squared Error (MSE)

$$\frac{\sum\left(y_i-{\hat{y}}_i\right)^2}{n}$$

- Root Mean Squared Error (RMSE)

$$\sqrt{\frac{\sum\left(y_i-{\hat{y}}_i\right)^2}{n}}$$

-  Mean Absolute Error (MAE)

$$\frac{\sum\left|y_i-{\hat{y}}_i\right|}{n}$$

- Mean Absolute Percentage Error (MAPE)

$$\frac{\sum\left|\frac{y_i-{\hat{y}}_i}{y_i}\right|}{n}\ \times100$$

- Mean Squared Percentage Error (MSPE)

$$\frac{\sum\left(\frac{y_i-{\hat{y}}_i}{y_i}\right)^2}{n}\ast100%$$

- (pseudo) R-squared |  ${R}^\mathbf{2}$ 

$$1-\frac{\sum\left(y_i-{\hat{y}}_i\right)^2}{\sum\left(y_i-\bar{y}\right)^2}$$

- Relative Squared Error (RSE)
$$\frac{\sum\left(y_i-{\hat{y}}_i\right)^2}{\sum\left(y_i-\bar{y}\right)^2}$$

- Relative Absolute Error (RAE)

$$\frac{\sum\left|y_i-{\hat{y}}_i\right|}{\sum\left|y_i-\bar{y}\right|}$$

\newpage

# Medidas de Classificação

- Coeficiente de Gini: 

$$G=1-\sum_{k=1}^K\left(\frac{n_k}{n}\right)^2$$



- Entropia :

$${\ }H=-\sum_{k=1}^K\frac{n_k}{n}\log\left(\frac{n_k}{n}\right)$$

- Entropia Normalizada (entre 0 e 1):

$$Hn=-\sum_{k=1}^K\frac{n_k}{n}\log\left(\frac{n_k}{n}\right)/\log(K)$$

- Deviance Nominal: 

$$DEV^{\mathrm{nom\ }}=-2\times\sum_{k=1}^K n_k\log\left(\frac{n_k}{n}\right)$$
- Precision/Positive Predictive Value  $\frac{TP}{TP+FP}$

- Recall/ Sensitivity/True Positive Rate $\frac{TP}{TP+FN}$

- Specificity/ True Negative Rate $\frac{TN}{FP+TN}$

- F1-Score $2\ \times\ \frac{\mathrm{Recall\ }\times\mathrm{\ Precision}}{\mathrm{Recall\ }+\mathrm{\ Precision}}\ \ =\ \ \ \frac{TP}{TP+\frac{1}{2}(FP+FN)}$

- Accuracy
 * Indica a proporção de observações corretamente classificadas
	+ No caso de 2 classes alvo $\frac{TP+TN}{TP+FN\ FP+TN)}$
	+ Em geral: soma dos elementos da diagonal da matriz de classificação sobre o total de observações

	

- Huberty index

$$\mathrm{Huberty\ }=\frac{\sum_{k=1}^{K}\frac{n_{kk}}{n}-p^{\mathrm{def\ }}}{1-p^{\mathrm{def\ }}} = \frac{Accuracy - p^{\mathrm{def\ }}}{1-p^{\mathrm{def\ }}}$$



